apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wbqgqs5zj-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f1a38b89470597411df00b57218aaa276db6d921@sha256:e32b129eaa3cbf1542a8362ac2e3bc86ee9a54db196ef3f3566e5985b6f60732
          name: container-image
